local tbl = 
{
	
	{
		actions = 
		{
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Toggle( \"cd\"、true、10000)\nself.used = true",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "CD",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 3,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 2,
				hpValue = 6000,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "HP CD kill",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 0,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "b6f0a7e0-4e0f-0e32-a5a1-50d45fbdf5bf",
	},
}



return tbl