local tbl = 
{
	
	{
		actions = 
		{
		},
		conditions = 
		{
		},
		enabled = false,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "       -Deep Dungeon-",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 0,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "16d43096-ef16-2bcd-bd76-b97af7146740",
	},
	
	{
		actions = 
		{
			
			{
				aType = 1,
				actionID = 7538,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					4,
					6,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 1,
				actionID = 7540,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					4,
					2,
					3,
					6,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 1,
				actionID = 7551,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					5,
					6,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsHohMaps() or DDCheck.IsPotDMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "MapCheck",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.Silence()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Silence Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsSilenceOnCD()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Is Silence on CD",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsTankJob()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "IsTankJobs",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsRangeJob()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "IsRangeJobs",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1092,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Silence",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 0,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "cd3e40a7-df66-0036-974a-fe7137c93c0f",
	},
	
	{
		actions = 
		{
			
			{
				aType = 1,
				actionID = 7540,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					3,
					4,
					7,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 1,
				actionID = 7863,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
					5,
					7,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 1,
				actionID = 7863,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = true,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					6,
					5,
					7,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsPotDMaps() or DDCheck.IsHohMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Map Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.Stun()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Stun Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsTankJob()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "IsTankJobs",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and not DDCheck.Silence()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Not Silence Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsMeleeJob()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "IsMeleeJobs",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.Silence()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Silence Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1092,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Stun",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "8b3ab845-0f45-1d24-882f-a0fdba8c0902",
	},
	
	{
		actions = 
		{
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					2,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Regen",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 20309,
				useItemName = "Sustaining Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "d(\"test\")",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					3,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_TensorRuin_CD",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Pot",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 1013637,
				useItemName = "Max-Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsPotDMaps()",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "potd map check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 75,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Self HP Regen",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 30,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Potd - Use HP Regen",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "6a80910a-dedf-757c-bf28-0dfef7c7a94d",
	},
	
	{
		actions = 
		{
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
					3,
					4,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Regen",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 23163,
				useItemName = "Empyrean Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
					3,
					4,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Pot",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 1023167,
				useItemName = "Super-Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1094,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 55,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsHohMaps()",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Map Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 50,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1094,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Item penalty",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Hoh - Use HP Regen",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "f65e0eca-d681-ba06-b1ed-3bac08912cf9",
	},
	
	{
		actions = 
		{
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_TensorRuin_CD",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Regen",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 20309,
				useItemName = "Sustaining Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Pot",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 1023167,
				useItemName = "Super-Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.RegenRequiredOnChannel()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Channel Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsPotDMaps()",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Map Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 3,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Potd - Pot on Channel",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "2957f9be-0819-8b53-aa92-0f739fefc50f",
	},
	
	{
		actions = 
		{
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_TensorRuin_CD",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Regen",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 23163,
				useItemName = "Empyrean Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Pot",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = true,
				useItemID = 1023167,
				useItemName = "Super-Potion (HQ)",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.RegenRequiredOnChannel()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Channel Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsHohMaps()",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "Map Check",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 3,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Hoh - Pot on Channel",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "457b7fb8-3666-b143-8afc-fced25046376",
	},
	
	{
		actions = 
		{
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Shotcall(DDCheck.AlertMessage(), true, 5, true)\nreturn true",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Alert",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.HasAlertMessage()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "has Alert message",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 3,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "AlertMessage",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 5000,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "0baa525c-aefb-8c91-a761-aa7bc1c64209",
	},
	
	{
		actions = 
		{
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Toggle(\"jumps\", false)\nself.used = true\n",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					4,
					3,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Toggle(\"jumps\", true)\nself.used = true\n",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					1,
					4,
					2,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsHohMaps() or DDCheck.IsPotDMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "MapCheck",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 6,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 3,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "near",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 6,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 3.0009999275208,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "far",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 7,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Safe Jump",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 500,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "83179e3b-c45a-74e6-bd3a-9e24ba30a0a2",
	},
	
	{
		actions = 
		{
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Toggle(\"jumps\", false)\nself.used = true\nreaction.eventConditionMismatch = true",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_RikuGNB_Jumps",
				gVarValue = 2,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 7,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 2,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsHohMaps() or DDCheck.IsPotDMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "MapCheck",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "Not In Combat",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 1000,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "77ad763b-7bb7-c4e7-b127-a759fab099e9",
	},
	
	{
		actions = 
		{
			
			{
				aType = 1,
				actionID = 7533,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					2,
					4,
					3,
					1,
					5,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_RikuGNB_Hotbar_Provoke",
				gVarValue = 1,
				ignoreWeaveRules = true,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Current Target",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 2,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 6,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 15.001000404358,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsHohMaps() or DDCheck.IsPotDMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "MapCheck",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and DDCheck.IsTankJob()",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "IsTankJobs",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 5,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 2,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 2,
				buffDuration = 0,
				buffID = 1092,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 1,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "provoke",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 500,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "84583c0f-99d4-e1b5-9ddd-c48730f7d97c",
	},
	
	{
		actions = 
		{
			
			{
				aType = 3,
				actionID = -1,
				actionLua = "",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					3,
					1,
					2,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "ACR_RikuPLD_CD",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Deselect",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = true,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
			
			{
				aType = 4,
				actionID = -1,
				actionLua = "AnyoneCore.Shotcall(\"Check HP\", true, 5, true)\nreturn true",
				allowInterrupt = false,
				atomicPriority = false,
				castAtMouse = false,
				castPosX = 0,
				castPosY = 0,
				castPosZ = 0,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterRadius = 8,
				clusterRange = 30,
				conditions = 
				{
					3,
					2,
					1,
				},
				endIfUsed = false,
				fallthrough = false,
				gVar = "",
				gVarValue = 1,
				ignoreWeaveRules = false,
				isAreaTarget = false,
				luaNeedsWeaveWindow = false,
				luaReturnsAction = false,
				name = "Alert",
				potType = 1,
				setTarget = false,
				showPositionPreview = false,
				stopCasting = false,
				stopMoving = false,
				targetContentID = -1,
				targetName = "",
				targetSubType = "Nearest",
				targetType = "Self",
				untarget = false,
				useForWeaving = false,
				useItem = false,
				useItemID = 0,
				useItemName = "",
				usePot = false,
				used = false,
				variableIsHover = false,
				variableTogglesType = 1,
			},
		},
		conditions = 
		{
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 2,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 2,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 90,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 1,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "",
				conditionType = 2,
				conditions = 
				{
				},
				contentid = 2007357,
				dequeueIfLuaFalse = false,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = -1,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "SilverChest",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
			
			{
				actionCDValue = 0,
				actionID = -1,
				buffCheckType = 1,
				buffDuration = 0,
				buffID = -1,
				buffIDList = 
				{
				},
				category = 4,
				channelCheckSpellID = -1,
				channelCheckSpellIDList = 
				{
				},
				channelCheckTimeRemain = 0,
				channelCheckType = 1,
				clusterMinPercent = false,
				clusterMinTarget = 1,
				clusterOriginalTarget = false,
				clusterRadius = 8,
				clusterRange = 30,
				comparator = 1,
				conditionLua = "return DDCheck ~= nil and (DDCheck.IsHohMaps() or DDCheck.IsPotDMaps())",
				conditionType = 8,
				conditions = 
				{
				},
				contentid = -1,
				dequeueIfLuaFalse = true,
				enmityValue = 0,
				eventArgOptionType = 1,
				eventArgType = 1,
				eventBuffDuration = 0,
				eventBuffID = -1,
				eventChatLine = "",
				eventEntityContentID = -1,
				eventEntityID = -1,
				eventEntityName = "",
				eventMarkerID = -1,
				eventOwnerContentID = -1,
				eventOwnerID = -1,
				eventOwnerName = "",
				eventSpellID = -1,
				eventSpellName = -1,
				eventTargetContentID = -1,
				eventTargetID = -1,
				eventTargetName = "",
				filterTargetSubtype = "Nearest",
				filterTargetType = "Self",
				gaugeIndex = 1,
				gaugeValue = 0,
				hpType = 1,
				hpValue = 0,
				inCombatType = 1,
				inRangeValue = 0,
				lastSkillID = -1,
				localmapid = 772,
				matchAnyBuff = false,
				minTargetPercent = false,
				mpType = 1,
				mpValue = 0,
				name = "MapCheck",
				partyHpType = 1,
				partyHpValue = 0,
				partyMpType = 1,
				partyMpValue = 0,
				partyTargetContentID = -1,
				partyTargetName = "",
				partyTargetNumber = 1,
				partyTargetSubType = "Nearest",
				partyTargetType = "All",
				rangeCheckSourceSubType = "Nearest",
				rangeCheckSourceType = "Self",
				rangeSourceContentID = -1,
				rangeSourceName = "",
				setEventTargetSubtype = 1,
				setFirstMatch = false,
			},
		},
		enabled = true,
		eventType = 1,
		execute = "",
		executeType = 1,
		lastUse = 0,
		luaNeedsWeaveWindow = false,
		luaReturnsAction = false,
		name = "SilverChest",
		randomOffset = 0,
		randomTimeout = 3,
		throttleTime = 250,
		time = 0,
		timeRandomRange = false,
		timeRange = false,
		timelineIndex = 0,
		timeout = 5,
		timerEndOffset = 0,
		timerOffset = 0,
		timerStartOffset = 0,
		used = false,
		uuid = "7213a69a-5a16-9eb5-8f3d-aa13a560ff54",
	},
}



return tbl